# Generated by Django 4.2.3 on 2023-11-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_employee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user.jpg', null=True, upload_to=''),
        ),
    ]
